#!/bin/bash
#PBS -N img2img_DiT
#PBS -q gpu
#PBS -l select=1:host=node9:ncpus=1:ngpus=1
#PBS -o $USER_DIR/Mafaz/Projects/img2img_DiT/img2img_DiT.out
#PBS -e $USER_DIR/Mafaz/Projects/img2img_DiT/img2img_DiT.err

cd "$PBS_O_WORKDIR"

source $USER_DIR/Mafaz/myenv/bin/activate

export CUDA_VISIBLE_DEVICES="$NODE9_MIG_UUID"

echo "Job started on $(hostname) at $(date)"
python3 -m training.train 
echo "Job finished at $(date)"